use_frameworks!

platform :ios, '13.0'

target 'WepinWidget_Example' do
  # pod 'WepinCommon', :path => '../../WepinCommon'
  # pod 'WepinCore', :path => '../../WepinCore'
  # pod 'WepinModal', :path => '../../WepinModal'
  # pod 'WepinLogin', :path => '../../WepinLogin'
  pod 'WepinCommon', '~> 1.1.2'
  pod 'WepinCore', '~> 1.1.2'
  pod 'WepinModal', '~> 1.1.2'
  pod 'WepinLogin', '~> 1.1.2'
  # pod 'WepinWidget', :path => '../'
  pod 'WepinWidget', '~> 1.1.2'

  target 'WepinWidget_Tests' do
    inherit! :search_paths

    
  end
end
