use_frameworks!

platform :ios, '13.0'

target 'WepinWidget_Example' do
  # pod 'WepinCommon', :path => '../../WepinCommon'
  # pod 'WepinStorage', :path => '../../WepinStorage'
  # pod 'WepinModal', :path => '../../WepinModal'
  # pod 'WepinNetwork', :path => '../../WepinNetwork'
  # pod 'WepinSession', :path => '../../WepinSession'
  # pod 'WepinLogin', :path => '../../WepinLogin'
  pod 'WepinCommon', '~> 1.1.0'
  pod 'WepinStorage', '~> 1.1.0'
  pod 'WepinModal', '~> 1.1.0'
  pod 'WepinNetwork', '~> 1.1.0'
  pod 'WepinSession', '~> 1.1.0'
  pod 'WepinLogin', '~> 1.1.0'
  pod 'WepinWidget', '~> 1.1.0'
  # pod 'WepinWidget', :path => '../'

  target 'WepinWidget_Tests' do
    inherit! :search_paths

    
  end
end
